### ISSUE TITLE
Convergence Check

### ISSUE THREAD

**Issue by xfang216** [seekrcentral/seekr2#17]
Dear SEEKR2 team,

I recently ran some SEEKR2 simulations of a protein looking at Ca binding to different EF hands. I came across a few issues when it comes to analyzing the results. They are described below and your help will be very much appreciated.

1. For one of the EF hand simulations, after running converge.py,  koff did not converge well, meaning it fluctuates across several orders of magnitude. Meanwhile, it did not return any output for the kon statictics. Running analyze.py returned this error "All post-simulation checks passed.
Printing results from MMVT SEEKR calculation
k_off (1/s): (5.8 ± 23.0) * 10^-22
k_ons :
  k_on (1/s * 1/M) to state 0 : (0.0 ± 0.0) * 10^+00
Traceback (most recent call last):
  File "/home/xfang2/Apps/seekr2/seekr2/analyze.py", line 763, in <module>
    analysis.print_results()
  File "/home/xfang2/Apps/seekr2/seekr2/analyze.py", line 602, in print_results
    delta_G_err = diss_constant_err*common_analyze.GAS_CONSTANT\
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
"
2. For another EF hand simulations, after running convergy.py, koff did not converge well either. Meanwhile kon showed nice convergence.
3. For the SMD simulations, it seems that it did not provide directional bias. Therefore, one thing I noticed is that while Ca was pulled away from the binding site, Ca actually moved closer to other parts of the protein. 

So I was wondering:
1. For the koff convergence issue, does it suggest longer simulation of the MD stage is needed?
2. For the kon issue, what would be an appropriate way to fix it?
3. After running analyze.py, several images were generated. For 'pi_alpha.png', 'p_i.png', and images under dirs 'N_ij' and 'R_i', I tried to look for descriptions on the website and the paper but no luck on that. Could you provide some explanations or sources to read up on them?
4. Regarding the SMD simulations, would it matter if the ligand is interacting with other parts of the protein even though it is away from the binding site? If so, is there a way to perform more sophisticated SMD simulations to a certain direction?

Thanks!
Xuan

**Comment by lvotapka** [comment]
Hi Xuan,

Your points are addressed below.

1. Yeah, these results look problematic. The error you got is probably a bug, but it's likely caused by insufficient statistics, probably not enough encounters in the BD stage. Would you please run converge.py on your system and paste the output here?

Your k-off looks very wrong: a k-off on the order of 10^-22 1/s is way too small. Probably the output of converge.py will tell us why this happened.

2. Would you attach the k-off convergence plot here, just so that I can see it?

3. Yes, this is a weakness of the SMD. I'd suggest either a) placing the center of the site deeper in the protein so that the Ca is more likely to exit through the correct path, or b) use a different method such as RAMD or Ratchet. Unfortunately, the latter two methods are relatively new so I don't have tutorials or instructions for how to use them. Why don't you try RAMD for at least one of your systems:

Here is an example command to run RAMD. You can find an explanation of the arguments by running HIDR with the "-h" argument:
```
python ~/seekrtools/seekrtools/hidr/hidr.py any /path/to/model.xml -M RAMD -p /path/to/bound_state.pdb -K 10.0 -c 0
```
You might consider changing the "-K" argument (RAMD force magnitude) to a smaller value since Ca is such a small ligand.

For the second list of questions:

1. The output of converge.py should tell us what is going wrong - although based on what you said about the SMD, it's likely that SMD is forcing the system out the wrong part of the protein - not the channel.
2. Let's see what converge.py tells us.
3. Thanks for the suggestion - I should indeed do this soon.
4. See the point above about RAMD or Ratchet.

**Comment by lvotapka** [comment]
Oh and based on the line numbers, I think you may be using an old version of SEEKR2. I'd suggest pulling and reinstalling the latest versions of SEEKR2 and SeekrTools

**Comment by xfang216** [comment]
Hi Lane,

Thanks for the response. Please see below for the convere.py outputs and results.

1. converge.y outputs:

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
All available options for --k_on_state include: [0]
No BD milestone has been provided for k_on_state. The BD milestone 0 has been chosen by default.
Processing interval 0 of 100
Processing interval 10 of 100
Processing interval 20 of 100
Processing interval 30 of 100
Processing interval 40 of 100
Processing interval 50 of 100
Processing interval 60 of 100
Processing interval 70 of 100
Processing interval 80 of 100
Processing interval 90 of 100
All plots have been saved to: /data/xfang2/seekrCalculation/cam_v2_1/site4/test/images_and_plots/
Molecular dynamics results:
 - Anchor 0: 
     Milestone transitions: 0->0 : 3636, 
     Milestone avg. transition time (ps): (0, 0) : 54.819,
     Convergence value: 2.8969e-02. 
     Converged? True
 - Anchor 1: 
     Milestone transitions: 0->1 : 4, 1->0 : 4, 
     Milestone avg. transition time (ps): 0 : 12418.071, 1 : 0.461,
     Convergence value: 1.4640e-01. 
     Converged? False
 - Anchor 2: 
     Milestone transitions: 1->2 : 13919, 2->1 : 13919, 
     Milestone avg. transition time (ps): 1 : 10.468, 2 : 3.865,
     Convergence value: 6.8371e-02. 
     Converged? True
 - Anchor 3: 
     Milestone transitions: 2->3 : 22558, 3->2 : 22558, 
     Milestone avg. transition time (ps): 2 : 6.258, 3 : 2.607,
     Convergence value: 1.7059e-02. 
     Converged? True
 - Anchor 4: 
     Milestone transitions: 3->4 : 7716, 4->3 : 7716, 
     Milestone avg. transition time (ps): 3 : 22.932, 4 : 2.682,
     Convergence value: 1.3517e-01. 
     Converged? False
 - Anchor 5: 
     Milestone transitions: 4->5 : 1234, 5->4 : 1234, 
     Milestone avg. transition time (ps): 4 : 159.807, 5 : 0.843,
     Convergence value: 6.8265e-02. 
     Converged? True
 - Anchor 6: 
     Milestone transitions: 6->5 : 5649, 5->6 : 5648, 
     Milestone avg. transition time (ps): 6 : 1.509, 5 : 33.884,
     Convergence value: 2.5109e-02. 
     Converged? True
 - Anchor 7: 
     Milestone transitions: 6->7 : 43, 7->6 : 43, 
     Milestone avg. transition time (ps): 6 : 4594.567, 7 : 0.767,
     Convergence value: 1.1278e-01. 
     Converged? False
 - Anchor 8: 
     Milestone transitions: 8->7 : 22806, 7->8 : 22805, 
     Milestone avg. transition time (ps): 8 : 2.603, 7 : 6.166,
     Convergence value: 2.0970e-02. 
     Converged? True
 - Anchor 9: 
     Milestone transitions: 8->9 : 17334, 9->8 : 17333, 
     Milestone avg. transition time (ps): 8 : 7.740, 9 : 3.798,
     Convergence value: 3.2512e-02. 
     Converged? True
 - Anchor 10: 
     Milestone transitions: 10->9 : 9049, 9->10 : 9048, 
     Milestone avg. transition time (ps): 10 : 2.188, 9 : 19.913,
     Convergence value: 3.6040e-02. 
     Converged? True
 - Anchor 11: 
     Milestone transitions: 10->11 : 2379, 11->10 : 2379, 
     Milestone avg. transition time (ps): 10 : 77.589, 11 : 1.964,
     Convergence value: 7.1653e-02. 
     Converged? True
 - Anchor 12: 
     Milestone transitions: 11->12 : 415, 12->11 : 415, 
     Milestone avg. transition time (ps): 11 : 478.883, 12 : 1.275,
     Convergence value: 8.2918e-02. 
     Converged? True
 - Anchor 13: 
     Milestone transitions: 12->13 : 15909, 13->12 : 15909, 
     Milestone avg. transition time (ps): 12 : 10.410, 13 : 2.162,
     Convergence value: 1.7960e-01. 
     Converged? False
 - Anchor 14: 
     Milestone transitions: 14->13 : 40515, 13->14 : 40515, 
     Milestone avg. transition time (ps): 14 : 2.973, 13 : 1.964,
     Convergence value: 1.0404e-02. 
     Converged? True
 - Anchor 15: 
     Milestone transitions: 15->14 : 38759, 14->15 : 38759, 
     Milestone avg. transition time (ps): 15 : 2.527, 14 : 2.633,
     Convergence value: 1.6810e-02. 
     Converged? True
 - Anchor 16: 
     Milestone transitions: 15->16 : 33253, 16->15 : 33253, 
     Milestone avg. transition time (ps): 15 : 2.176, 16 : 3.839,
     Convergence value: 9.1745e-02. 
     Converged? True
 - Anchor 17: 
     Milestone transitions: 16->17 : 47955, 17->16 : 47954, 
     Milestone avg. transition time (ps): 16 : 2.178, 17 : 1.992,
     Convergence value: 5.9184e-03. 
     Converged? True
 - Anchor 18: 
     Milestone transitions: 18->17 : 39352, 17->18 : 39351, 
     Milestone avg. transition time (ps): 18 : 2.378, 17 : 2.702,
     Convergence value: 1.3767e-02. 
     Converged? True
 - Anchor 19: 
     Milestone transitions: 19->18 : 40341, 18->19 : 40341, 
     Milestone avg. transition time (ps): 19 : 1.729, 18 : 3.229,
     Convergence value: 1.0695e-02. 
     Converged? True
 - Anchor 20: 
     Milestone transitions: 20->19 : 31339, 19->20 : 31338, 
     Milestone avg. transition time (ps): 20 : 1.501, 19 : 4.881,
     Convergence value: 3.0448e-02. 
     Converged? True
 - Anchor 21: 
     Milestone transitions: 20->21 : 20184, 21->20 : 20184, 
     Milestone avg. transition time (ps): 20 : 7.977, 21 : 1.932,
     Convergence value: 2.7945e-02. 
     Converged? True
 - Anchor 22: 
     Milestone transitions: 21->22 : 37559, 22->21 : 37559, 
     Milestone avg. transition time (ps): 21 : 3.785, 22 : 1.540,
     Convergence value: 1.3984e-02. 
     Converged? True
 - Anchor 23: 
     Milestone transitions: 22->23 : 32920, 23->22 : 32920, 
     Milestone avg. transition time (ps): 22 : 4.769, 23 : 1.306,
     Convergence value: 2.7415e-02. 
     Converged? True
 - Anchor 24: 
     Milestone transitions: 23->24 : 39640, 24->23 : 39640, 
     Milestone avg. transition time (ps): 23 : 3.862, 24 : 1.184,
     Convergence value: 2.3995e-02. 
     Converged? True
 - Anchor 25: 
     Milestone transitions: 25->24 : 29430, 24->25 : 29429, 
     Milestone avg. transition time (ps): 25 : 0.972, 24 : 5.824,
     Convergence value: 3.8471e-02. 
     Converged? True
 - Anchor 26: 
     Milestone transitions: 25->26 : 45786, 26->25 : 45785, 
     Milestone avg. transition time (ps): 25 : 2.360, 26 : 2.008,
     Convergence value: 6.1604e-03. 
     Converged? True
 - Anchor 27: 
     Milestone transitions: 26->27 : 45866, 27->26 : 45866, 
     Milestone avg. transition time (ps): 26 : 2.238, 27 : 2.123,
     Convergence value: 4.0497e-03. 
     Converged? True
 - Anchor 28: 
     Milestone transitions: 27->28 : 34388, 28->27 : 34387, 
     Milestone avg. transition time (ps): 27 : 4.642, 28 : 1.174,
     Convergence value: 2.1748e-02. 
     Converged? True
 - Anchor 29: 
     Milestone transitions: 28->29 : 36459, 29->28 : 36458, 
     Milestone avg. transition time (ps): 28 : 4.266, 29 : 1.220,
     Convergence value: 1.0262e-02. 
     Converged? True
 - Anchor 30: 
     Milestone transitions: 30->29 : 26596, 29->30 : 26595, 
     Milestone avg. transition time (ps): 30 : 0.962, 29 : 6.558,
     Convergence value: 2.3943e-02. 
     Converged? True
 - Anchor 31: 
     Milestone transitions: 31->30 : 38088, 30->31 : 38088, 
     Milestone avg. transition time (ps): 31 : 1.249, 30 : 4.002,
     Convergence value: 1.9600e-02. 
     Converged? True
Brownian dynamics results:
 - b-surface reaction counts:
     to milestone 32: 3140
     to milestone 31: 3005
     to escaped: 6995
     to stuck: 0
     to milestone 30: 0
 - BD milestone 0 reaction counts:
     to milestone 30: 0
     to escaped: 3005


2. k_off convergence plot:
![k_off_convergence](https://user-images.githubusercontent.com/63471763/184420839-82fc9ecd-fe1b-48a2-971d-b433805ea7d4.png)

And yes, I'll try the RAMD too.

Thanks!
Xuan

**Comment by lvotapka** [comment]
I think that some of these problems will be solved by using the most updated version of the SEEKR2 software. As for the convergence results, I see that there are relatively few transitions in anchor_1.

Based on the analyze.py output, the converge.py output, and the plot you sent, I'll bet that the SMD is forcing the ligand out the wrong way. I've encountered this problem before also.

Let me know how RAMD performs, or if you have any trouble getting it to work.

**Comment by lvotapka** [comment]
Hi @xfang216, did this error ultimately get resolved?

**Comment by xfang216** [comment]
Hi @lvotapka, thanks for checking. Unfortunately our cluster administrator is still in the process of updating the package so I haven't been able to test it out. Will keep you updated once I get the results.

**Comment by xfang216** [comment]
> 

Hi Lane,

I was testing RAMD yet ran into the following issue:

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Assigning pdb file x.pdb to anchor 0
The following procedure will be executed:
RAMD force constant is 3.0 kcal/(A mol)
RAMD from anchor 0 to anchor [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Estimated total simulation time: 20.000 ns
running RAMD from anchor 0 to anchor [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekrtools/seekrtools/hidr/hidr.py", line 366, in <module>
    hidr(model, destination, pdb_files, dry_run, equilibration_steps, 
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekrtools/seekrtools/hidr/hidr.py", line 208, in hidr
    ns_per_day = hidr_simulation.run_RAMD_simulation(
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/seekrtools-0+untagged.65.g549ac37-py3.8.egg/seekrtools/hidr/hidr_simulation.py", line 639, in run_RAMD_simulation
    assert not found_anchor, "Found system in two different "\
AssertionError: Found system in two different anchors in the same step.


Could you enlighten me on what might be causing this?

Thank you!

**Comment by lvotapka** [comment]
Yeah this is a bug that should now be fixed in the dev branch of seekrtools (not seekr2). So go ahead and pull from the dev branch and reinstall seekrtools, and let me know how it goes.

**Comment by xfang216** [comment]
Is there a good way to do a clean uninstallation of seekrtools and then reinstall it?

**Comment by lvotapka** [comment]
You shouldn't need to do that, you should be able to just run "python setup.py install" right in the seekrtools/ directory.

But if you need a clean install, I suppose you could do "conda remove seekrtools" first.

**Comment by xfang216** [comment]
Hi Lane, 

It seems that when our cluster administrator tried to pull the dev branch, it showed only the master branch. Could you provide some instructions on how it should be done?

Thank you!

**Comment by lvotapka** [comment]
The dev branch is definitely there. Did he forget to make his own dev branch and do a checkout?

```
git branch dev
git checkout dev
git pull origin dev
```

**Comment by xfang216** [comment]
Hi Lane,

Thanks for your suggestion, that worked. Now I ran into another issue when using prepare.py.

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
NOsh:  Bad dime[0]  = 81 (3 nlev)!
NOsh:  Reset dime[0] to 65 and (nlev = 4).
NOsh:  Bad dime[1]  = 81 (3 nlev)!
NOsh:  Reset dime[1] to 65 and (nlev = 4).
NOsh:  Bad dime[2]  = 81 (3 nlev)!
NOsh:  Reset dime[2] to 65 and (nlev = 4).
Vpmg_ctor2: 
Warning: External energies are not used in BCFL_MAP calculations!
Vpmg_ctor2: 
Warning: External energies are not used in BCFL_MAP calculations!
Vpmg_ctor2: 
Warning: External energies are not used in BCFL_MAP calculations!
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekr2/seekr2/prepare.py", line 75, in <module>
    model, xml_path = prepare(model_input, force_overwrite)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekr2/seekr2/prepare.py", line 44, in prepare
    base.save_model(model, xml_path)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/common_base.py", line 1004, in save_model
    model.serialize(model_file, xml_header=dont_modify_warning)
TypeError: serialize() got an unexpected keyword argument 'xml_header'


How can this be fixed? Thanks!

**Comment by lvotapka** [comment]
You probably need to upgrade Abserdes:

```
pip install --upgrade abserdes
```

**Comment by xfang216** [comment]
Thanks Lane, that fixed it. I then ran hidr.py but got the following error:

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Assigning pdb file x.pdb to anchor 0
The following procedure will be executed:
RAMD force constant is 3.0 kcal/(A mol)
RAMD from anchor 0 to anchor [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Estimated total simulation time: 20.000 ns
running RAMD from anchor 0 to anchor [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekrtools/seekrtools/hidr/hidr.py", line 434, in <module>
    hidr(model, destination, pdb_files, toy_coordinates, dry_run, 
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekrtools/seekrtools/hidr/hidr.py", line 226, in hidr
    ns_per_day = hidr_simulation.run_RAMD_simulation(
TypeError: run_RAMD_simulation() got an unexpected keyword argument 'steps_per_RAMD_update'

The seekrtools has been pulled from the dev branch and updated. Is this issue related to another package?

**Comment by lvotapka** [comment]
Did you run

```
python setup.py install
```

Within the seekrtools/ directory after pulling from the dev branch?

**Comment by xfang216** [comment]
You're right. It wasn't run. It is run now. But there's another issue

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Assigning pdb file x.pdb to anchor 0
The following procedure will be executed:
RAMD force constant is 3.0 kcal/(A mol)
RAMD from anchor 0 to anchor [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Estimated total simulation time: 20.000 ns
running RAMD from anchor 0 to anchor [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekrtools/seekrtools/hidr/hidr.py", line 434, in <module>
    hidr(model, destination, pdb_files, toy_coordinates, dry_run, 
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekrtools/seekrtools/hidr/hidr.py", line 226, in hidr
    ns_per_day = hidr_simulation.run_RAMD_simulation(
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/seekrtools-0+untagged.93.gd779cf7-py3.8.egg/seekrtools/hidr/hidr_simulation.py", line 600, in run_RAMD_simulation
    simulation = openmm_ramd.RAMDSimulation(
TypeError: __init__() got an unexpected keyword argument 'ramdSteps'

**Comment by lvotapka** [comment]
Ah you should pull and install the latest version of openmm_ramd from the dev branch there too.

**Comment by xfang216** [comment]
I see. But it looks like there's just the master branch there. Is this the right repo (https://github.com/seekrcentral/openmm_ramd)?

**Comment by lvotapka** [comment]
Oh sorry about that - yes you want the master branch.

**Comment by xfang216** [comment]
Hi Lane, 

Our administrator did the following but the issue remains:
git clone https://github.com/seekrcentral/openmm_ramd.git
cd openmm_ramd
python setup.py install

Looking at the openmm_ramd.py under openmm_ramd/openmm_ramd though, it looks like the __init__ function does not contain the 'ramdSteps' argument. Could this be the reason?

**Comment by lvotapka** [comment]
I might not have pushed those latest changes. Yry to pull and reinstall one more time...

**Comment by xfang216** [comment]
That did the trick. Thanks Lane. I can play around with ramd now.

**Comment by xfang216** [comment]
Hi Lane,

I played around with the RAMD but ran into a few issues.

1. When running prepare.py, I got these warnings:
NOsh:  Bad dime[0]  = 81 (3 nlev)!
NOsh:  Reset dime[0] to 65 and (nlev = 4).
NOsh:  Bad dime[1]  = 81 (3 nlev)!
NOsh:  Reset dime[1] to 65 and (nlev = 4).
NOsh:  Bad dime[2]  = 81 (3 nlev)!
NOsh:  Reset dime[2] to 65 and (nlev = 4).

2. When running hidr.py, I got the following errors:
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Assigning pdb file x.pdb to anchor 0
The following procedure will be executed:
RAMD force constant is 1.0 kcal/(A mol)
RAMD from anchor 0 to anchor [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Estimated total simulation time: 20.000 ns
running RAMD from anchor 0 to anchor [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
recomputing force!
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekrtools/seekrtools/hidr/hidr.py", line 434, in <module>
    hidr(model, destination, pdb_files, toy_coordinates, dry_run, 
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekrtools/seekrtools/hidr/hidr.py", line 226, in hidr
    ns_per_day = hidr_simulation.run_RAMD_simulation(
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/seekrtools-0+untagged.93.gd779cf7-py3.8.egg/seekrtools/hidr/hidr_simulation.py", line 640, in run_RAMD_simulation
    simulation.RAMD_step(steps_per_RAMD_update)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/openmm_ramd-0+untagged.10.g7f01e3c-py3.8.egg/openmm_ramd/openmm_ramd.py", line 200, in RAMD_step
    self.step(numSteps)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/openmm/app/simulation.py", line 134, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/openmm/app/simulation.py", line 236, in _simulate
    self._generate_reports(wrapped, True)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/openmm/app/simulation.py", line 258, in _generate_reports
    reporter.report(self, state)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/openmm/app/pdbreporter.py", line 98, in report
    PDBFile.writeModel(simulation.topology, state.getPositions(), self._out, self._nextModel)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/openmm/app/pdbfile.py", line 335, in writeModel
    raise ValueError('Particle position is NaN')
ValueError: Particle position is NaN


My system is a Ca2+-binding protein and I'm assigning one single Ca2+ as the ligand. The regular SMD.py and seekr simulatiosn worked fine for this system though. Also, I ran the toy system and all seemed fine so I don't think there's a problem with the packages. So do you think having one single atom as the ligand might be why the issues and do you have any suggestions on how to debug/fix this? 

Thanks.

**Comment by lvotapka** [comment]
Hi @xfang216 ,

Your points are addressed below:

1. I usually ignore these warnings, because they are coming from Browndye's automatic APBS input generator/runner, and Browndye generates several layers of electrostatics grids and superimposes them - sometimes the grids are focused on a particular area of a molecule (not encompassing the entire molecule), and sometimes they have low resolution for the outermost grids. APBS might throw warnings about either of these situations. Here's a link where they talk more about these warnings: https://sourceforge.net/p/apbs/mailman/message/30673990/. If you're really concerned, you might get more explanation from the Browndye developer.

2. It's possible that you might be using too large of a force constant. Have you tried using a much smaller number? If you still get a NaN error with a small force constant, it's possible that the starting structure is unstable or the box vectors are wrong.

**Comment by xfang216** [comment]
Hi Lane,

It indeed was an issue with the starting structure. I then ran minimization and equilibration of the structure and used the equilibrated structure for RAMD. That worked. However, I ran into a new issue. During the simulation, the ligand kept bouncing between anchor_0 and anchor_1. It wouldn't move into anchor_2. If I simulate only anchor_2, it keeps saying 'recomputing force!'. At the end of the log file, it says:

Warning: anchor 2 has no starting PDB structures.
Warning: anchor 3 has no starting PDB structures.
Warning: anchor 4 has no starting PDB structures.
Warning: anchor 5 has no starting PDB structures.
Warning: anchor 6 has no starting PDB structures.
Warning: anchor 7 has no starting PDB structures.
Warning: anchor 8 has no starting PDB structures.
Warning: anchor 9 has no starting PDB structures.
Warning: anchor 10 has no starting PDB structures.
Warning: anchor 11 has no starting PDB structures.
Warning: anchor 12 has no starting PDB structures.
Warning: anchor 13 has no starting PDB structures.
Warning: anchor 14 has no starting PDB structures.
Warning: anchor 15 has no starting PDB structures.
Warning: anchor 16 has no starting PDB structures.
Benchmark: 18.735888896878826 ps ns/day
Renaming model.xml to model_pre_hidr_1.xml
Saving new model.xml
Assigning pdb file x.pdb to anchor 0

I tried this with different force constants from 0.1 to 10 but they behaved the same. Do you have any insights into what might be causing this and how to debug?

Thanks!

**Comment by lvotapka** [comment]
It sounds like RAMD is not able to push the ligand out beyond anchor 2. If it's really tightly bound, then a larger force constant would eventually do it. But 10 is already quite big, especially for just a single calcium ion. Are you sure that the atom selections for ligand and site are correct? What radii are you using? You might also try adjusting or adding anchors between anchor 1 and 2 to see if you can triangulate the problem. You can also visualize the RAMD trajectory by looking in anchor_0/building/hidr_traj_ramd.pdb and see if something strange is going on.

**Comment by xfang216** [comment]
Hi Lane,

I managed to generate some more reasonable starting structures for seekr sims. However when I ran run.py, I encountered the following error:

anchor 0 has not run the minimum number of steps 0 of 100000000 in swarm index None
running anchor_index: 0 restart: False total_simulation_length: 100000000 num_transitions: 0 swarm index: None
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekr2/seekr2/run.py", line 853, in <module>
    run(model, instruction, min_total_simulation_length, 
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekr2/seekr2/run.py", line 615, in run
    run_openmm(model, anchor_index, restart, 
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekr2/seekr2/run.py", line 487, in run_openmm
    runner.run(sim_openmm_obj, restart, load_state_file, restart_index)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/runner_openmm.py", line 451, in run
    self.run_mmvt(traj_filename)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/runner_openmm.py", line 529, in run_mmvt
    saveCheckpoint(self.sim_openmm, self.restart_checkpoint_filename)
  File "/cm/shared/apps/anaconda3/envs/SEEKR/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/runner_openmm.py", line 229, in saveCheckpoint
    sim_time = sim_openmm.simulation.context.getTime().value_in_unit(
AttributeError: 'Context' object has no attribute 'getTime'

Is this an update issue?

Thanks!

**Comment by lvotapka** [comment]
It sounds like you are using a version of OpenMM that is too old. What version of OpenMM are you using?

**Comment by xfang216** [comment]
It should be 7.6

**Comment by lvotapka** [comment]
That should be a usable version. Did you install from source or conda-force?

In the correct conda environment, open up Python and type:

```
import openmm
print(openmm.__version__)
```

And paste the result here.

**Comment by xfang216** [comment]
Hi Lane, below is the result. I did not personally install it but I think our administrator installed it following the instructions on https://seekr2.readthedocs.io/en/latest/installation.html using conda.

(SEEKR) xfang2@Faust:~/SCRATCH/seekrCalculation$ python
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openmm
>>> print(openmm.__version__)
7.6

**Comment by lvotapka** [comment]
That's strange, maybe it doesn't work with 7.6.0. Any chance you could get your admin to upgrade you to OpenMM 7.7.0? I'm using that version and SEEKR2 works fine.

**Comment by xfang216** [comment]
I see. I will ask him to do that and keep you posted. Thank you!

**Comment by lvotapka** [comment]
Good news, @xfang216: I figured out what was causing the difficulties in installing the SEEKR2 plugin using Conda. You should now be able to install from Conda without needing to install from source.

**Comment by xfang216** [comment]
Hi Lane, that's great news. I will let our administrator know. Thanks!
